server:
  port: 8002


spring:
  application:
    name: cloud-provider-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.31.110:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.107:8848

#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.yout.cloud.domains