server:
  port: 80

spring:
  application:
    name: cloud-consumer-web
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.110:8848

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic